# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

        config.vm.define :servidor do |servidor|
                servidor.vm.box = "bento/ubuntu-22.04"
                servidor.vm.network :private_network, ip: "192.168.50.3"
                servidor.vm.hostname = "servidor1"
        end
        config.vm.define :esclavo do |esclavo|
                esclavo.vm.box = "bento/ubuntu-22.04"
                esclavo.vm.network :private_network, ip: "192.168.50.4"
                esclavo.vm.hostname = "esclavo"
        end
        config.vm.define :servidor2 do |servidor2|
                servidor2.vm.box = "bento/ubuntu-22.04"
                servidor2.vm.network :private_network, ip: "192.168.50.2"
                servidor2.vm.hostname = "servidor2"
        end
        config.vm.define :dnsseguro do |dnsseguro|
                dnsseguro.vm.box = "bento/ubuntu-22.04"
                dnsseguro.vm.network :private_network, ip: "192.168.50.5"
                dnsseguro.vm.hostname = "dnsseguro"
        end
end